name: Build and deploy Docker app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Como usas imagen pública nginx:alpine no hace falta login

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: devops-html-contenedor-julio2025
          slot-name: production
          images: nginx:alpine
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
