- name: Login to Docker Hub
  uses: docker/login-action@v2
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

- name: Build and push Docker image
  run: |
    docker build -t xoanabella/devops-html-julio2025:latest .
    docker push xoanabella/devops-html-julio2025:latest

- name: Deploy Docker container to Azure App Service
  run: |
    az webapp config container set \
      --name devops-html-julio2025 \
      --resource-group plan_formacon_devops \
      --container-image-name xoanabella/devops-html-julio2025:latest

- name: Restart App Service
  run: |
    az webapp restart --name devops-html-julio2025 --resource-group plan_formacon_devops
